name: Bandit Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/1 * * * *'  # Scheduled run every 1 minute

jobs:
  bandit:
    permissions:
      contents: read  # Required for actions/checkout to fetch code
      security-events: write  # Required to upload SARIF results
      actions: read  # Required for a private repository

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python and Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit security analysis
        run: |
          bandit -r . -f json -o bandit-output.json -v

      - name: Convert Bandit output to SARIF
        run: |
          pip install bandit-sarif
          bandit-sarif bandit-output.json results.sarif

      - name: Upload Bandit results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
