name: Bandit Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/1 * * * *'  # Scheduled run every 1 minute

jobs:
  bandit:
    permissions:
      contents: read  # Required for actions/checkout to fetch code
      security-events: write  # Required to upload SARIF results
      actions: read  # Required for a private repository

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python, Bandit, and json2sarif
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install json2sarif

      - name: Run Bandit security analysis
        run: |
          bandit -r . -f json -o bandit-output.json -v --exit-zero

      - name: Convert Bandit output to SARIF
        run: |
          json2sarif -i bandit-output.json -o results.sarif

      - name: Upload Bandit results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
